// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDelK_1Sc3kaXfS-KMAe8rw3v36WMZp8A0',
    appId: '1:1053442770629:web:8fa49841148988471192ac',
    messagingSenderId: '1053442770629',
    projectId: 'amuzi-5f9d4',
    authDomain: 'amuzi-5f9d4.firebaseapp.com',
    storageBucket: 'amuzi-5f9d4.appspot.com',
    measurementId: 'G-D34JPTXGCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDExgDjt2R9QeI9IRjXH-9a4mm-tviiXM8',
    appId: '1:1053442770629:android:573ed8cae666c8d81192ac',
    messagingSenderId: '1053442770629',
    projectId: 'amuzi-5f9d4',
    storageBucket: 'amuzi-5f9d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChIm3jlDaddFUmvpFrzcXeOAMr8Xd878M',
    appId: '1:1053442770629:ios:2fd04d98b04c933a1192ac',
    messagingSenderId: '1053442770629',
    projectId: 'amuzi-5f9d4',
    storageBucket: 'amuzi-5f9d4.appspot.com',
    androidClientId: '1053442770629-eqisq56ppghqj4siksp0pckk4tocmp7n.apps.googleusercontent.com',
    iosClientId: '1053442770629-al7ar09vhgsj2827rccstuobej9ng0jr.apps.googleusercontent.com',
    iosBundleId: 'com.ott.amuziapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChIm3jlDaddFUmvpFrzcXeOAMr8Xd878M',
    appId: '1:1053442770629:ios:2fd04d98b04c933a1192ac',
    messagingSenderId: '1053442770629',
    projectId: 'amuzi-5f9d4',
    storageBucket: 'amuzi-5f9d4.appspot.com',
    androidClientId: '1053442770629-eqisq56ppghqj4siksp0pckk4tocmp7n.apps.googleusercontent.com',
    iosClientId: '1053442770629-al7ar09vhgsj2827rccstuobej9ng0jr.apps.googleusercontent.com',
    iosBundleId: 'com.ott.amuziapp',
  );
}
