// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyugNhMh9OLugoGGdwEWgdSCZ_RS7EIO4',
    appId: '1:663533434843:web:c6ae9531d361de38fe99fe',
    messagingSenderId: '663533434843',
    projectId: 'mitwatv-3c8bf',
    authDomain: 'mitwatv-3c8bf.firebaseapp.com',
    storageBucket: 'mitwatv-3c8bf.appspot.com',
    measurementId: 'G-8V44NX4CJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI_Wj-P_Lfo-vRIIpl5wIG48yZdB_werw',
    appId: '1:663533434843:android:025c021a2250cc0afe99fe',
    messagingSenderId: '663533434843',
    projectId: 'mitwatv-3c8bf',
    storageBucket: 'mitwatv-3c8bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeHiYJJtmhC-s7OO5zAAcRoQXh7EvCkN4',
    appId: '1:663533434843:ios:4b839fe5a9fc09f1fe99fe',
    messagingSenderId: '663533434843',
    projectId: 'mitwatv-3c8bf',
    storageBucket: 'mitwatv-3c8bf.appspot.com',
    androidClientId: '663533434843-9g2v2lca9fntsitgi8okom2t6hj2e5il.apps.googleusercontent.com',
    iosClientId: '663533434843-aqnt2cv02epkfn98n59ajeaur73gr2iv.apps.googleusercontent.com',
    iosBundleId: 'com.release.mitwatvapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeHiYJJtmhC-s7OO5zAAcRoQXh7EvCkN4',
    appId: '1:663533434843:ios:4b839fe5a9fc09f1fe99fe',
    messagingSenderId: '663533434843',
    projectId: 'mitwatv-3c8bf',
    storageBucket: 'mitwatv-3c8bf.appspot.com',
    androidClientId: '663533434843-9g2v2lca9fntsitgi8okom2t6hj2e5il.apps.googleusercontent.com',
    iosClientId: '663533434843-aqnt2cv02epkfn98n59ajeaur73gr2iv.apps.googleusercontent.com',
    iosBundleId: 'com.release.mitwatvapp',
  );
}
